name: ROS-noetic Build Check

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: setup ROS1
      uses: ros-tooling/setup-ros@v0.6
      with:
        required-ros-distributions: noetic
    - name: build
      uses: ros-tooling/action-ros-ci@v0.3
      with:
        package-name: icm_20948 serial
        target-ros1-distro: noetic
        vcs-repo-file-url: "${{ github.workspace }}/pupbot.rosinstall"
        skip-tests: true
